# Generated by Django 3.1.3 on 2020-12-02 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('volumen', models.CharField(max_length=13, verbose_name='Volumen')),
                ('genre', models.ManyToManyField(to='catalogo.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Mangaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_muerte', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='MangaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'Stock Disponible'), ('n', 'Stock no Disponible')], default='s', max_length=2)),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.manga')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='manga',
            name='mangaka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.mangaka'),
        ),
    ]
