# Generated by Django 3.1.3 on 2020-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201203_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genero',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='genre',
        ),
        migrations.AddField(
            model_name='manga',
            name='genero',
            field=models.ManyToManyField(to='catalogo.Genero'),
        ),
        migrations.CreateModel(
            name='Figuras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('marca', models.ManyToManyField(to='catalogo.Marca')),
            ],
        ),
    ]
