# Generated by Django 3.1.3 on 2020-12-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201203_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MangaInstance',
        ),
    ]
