# Generated by Django 3.1.3 on 2020-12-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_delete_mangainstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangaka',
            options={},
        ),
        migrations.AddField(
            model_name='figuras',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mangaka',
            name='fecha_muerte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
