# Generated by Django 3.1.3 on 2020-12-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201203_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
