# Generated by Django 3.1.2 on 2021-05-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20210517_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='receta',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.tipo'),
        ),
    ]
