# Generated by Django 3.2.3 on 2021-06-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20210626_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.comuna'),
        ),
    ]
