# Generated by Django 3.2.3 on 2021-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_negocio_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='direccion',
            field=models.TextField(default='halo', max_length=1000),
        ),
        migrations.AddField(
            model_name='negocio',
            name='web',
            field=models.TextField(default='halo', max_length=1000),
        ),
    ]
