# Generated by Django 3.2.3 on 2021-06-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20210626_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
