# Generated by Django 3.2.3 on 2021-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_alter_negocio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
