# Generated by Django 3.2.3 on 2021-06-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_negocio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='image',
            new_name='imagen',
        ),
    ]
