# Generated by Django 3.2.2 on 2021-06-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_rename_image_negocio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='user',
        ),
    ]
