# Generated by Django 3.2.2 on 2021-06-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_remove_negocio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='web',
            field=models.TextField(max_length=1000),
        ),
    ]
