# Generated by Django 3.2.2 on 2021-06-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_auto_20210626_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='imagen',
            field=models.ImageField(blank=True, default='descarga.png', null=True, upload_to=''),
        ),
    ]
